namespace SpriteKind {
    export const Customer = SpriteKind.create()
}
let Fish = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . c c c c . . . . 
    . . . . . . c c 6 6 6 6 c . . . 
    . . . . . c c c c c c 6 c . . . 
    . . . . c c 3 3 3 3 6 c c . . . 
    . . . c 3 6 3 3 3 3 3 9 c . a c 
    . . c 3 3 3 9 3 3 3 3 6 9 c 3 c 
    . c 3 3 3 3 9 3 3 3 3 3 9 c 3 c 
    a 3 3 3 3 3 9 3 3 3 3 3 9 3 3 a 
    a 3 3 f a 3 9 c c 3 3 3 9 a 3 a 
    a 3 3 f f 3 9 3 3 a 3 3 6 a 3 a 
    . a 3 3 3 3 9 c 3 a 3 6 a a a a 
    . . a a 3 6 3 3 a a 3 c a c . . 
    . . . . a a 3 3 3 3 c 9 6 c . . 
    . . . . . . a a a a 9 9 9 c . . 
    . . . . . . . . . . c c c . . . 
    `, SpriteKind.Customer)
let Octopus = sprites.create(img`
    ................................................................
    ......................................fffffffff.................
    ......................ffff..........ffaaaaaaaaaff...............
    .....................ffcccff.......faaaaaaaa333aaf..............
    .....................ffffccf......faaa5aaaaa35333af.............
    .....................f.ffccf.....faaaaaaa5aa333333af.....ffff...
    ........................fccf.....faaaaaaaaaa3333333f...ffccccff.
    .......................ffcf.....faaa5aaaaaaa3333333af..fccccccf.
    .......................fccf.....faaaaaaaaaaaaaa3333af..ffccffff.
    .......................fccf.....faaa5aaaaa5aaaa353aaf...fcff....
    ......................ffccf.....faaaaaaaaaaaaaaaaaaaf...fcf.....
    ......................ffcf......faaaaaaaaaaaaaa5aaaaf...fcf.....
    ...........fffffff....fccf.....ffaaaaaaaaaaaaaaaaaaaf...fcf.....
    .....ff...ffaaaaaf...ffccfff...faaaaaaaaaaaaaaaaaaaaf...fcf.....
    ....fff.aaaa5aaaaff..fcccccf..ffaaaaaaaaaaaaaaaaaaaaf..fccf.....
    ....fafaaa5aaaaaaaf..fcccccf..faaaaaaaaaaaaaaaaaaaaaf..fccf.....
    ....faaa5aaaaaaaaaf..fcccccff.faaf81faaaaaaaaaaaaaaf..fcccf.....
    ....ffaaaaafffaaaff..fcccccccffaff86faaaaaafffffaaaf..fcccf.....
    ....3faaaafffaaaaf...fcccccccfaffff6faaaaaafff61aaaf..fccccf....
    .....3ffff..faaaff...fccccccffaffff6faaaaaafff86faaf.fcccccf....
    ........33..faaaf....fcccccfaafffffffaaaaaaffff6ffa..fccccf.....
    ............faaaf....ffcccfaaaffffffaaaaaaaffff666a..fcccfaf....
    ...........ffaaaf.....fccfaaaafffffaaaaaaaafffff81a.fcccfaaff...
    ...........faaaaf......ffaaaaaaffffaaaaaaaaafffffff.fccfaaaaaf..
    ...........faaaaf......faaaaaaaaaaaaaaaaaaaaaaffff.fccffaaffff..
    ...........faaaaf......faaaaaaaaaaaaaaaaaaaaaaffff.fccfaaaf..f..
    ...........faaaaf.....f5aaaaaaaaaafaaafaaaaaaaaaf.fcccfaa5f.....
    ...........faaaaff....f51aaaaaaaaaafffaaaaaaaaaaf.fcccfaaaaf....
    ...........faaaaaff...fa55aaaaaaaaaaaaaaaaaaaaafcfccccffaaaf....
    ...........faaaaaafffffaa51aaaaaaaaaaaaaaaaaaaafcccccccffaaf3...
    ............faaaaaaccccaa55aaaaaaaaaaaaaaaaa555cccccccf.faaf3...
    .............faaaccccccaaa51aaaaaaaaaaaaa551afcccccccf..fa5f....
    ..............faaccccccaaaa551aaaaaaaaaa55aaafccccccff..faaaf...
    ...............ffccccccaaaaaa555555555551aaaafccccff....faaaf...
    .........ff.....fffcccfaaaaaaaaa4a3aaaaaaaaaaffffff.....faaaf3..
    ........ffaffff....fffccaaaaaaaaa4aaaaaaaaaaaf.........faa5af3..
    ...ff...faaaaaaff...fcccfaaaaaaa431aaaaaaaaaaaf........faaaaf...
    .ffaf...fa5aaaaaafffccccfaaaaaa33333aaaaaaaaaaf........faaaaf...
    .faaf..ffaaaaaaaaaaacccfaaaaaaa44331aaaaaaaaaaaf......faaaaff...
    .faff..faaaaaaafffffffffaaaaaaa34343aaaaaaaaaaaaff...ffaaaaf....
    .faf...faaaaafff.......faaaaaaacccfaaaaaaaaaaaaaaaffffaaaaaf....
    .faf..ffaaaaaf.........faaaaaafcccfaaaaaaaaaacccaaaaaaaaaaaf....
    .ffafffaa5aaaf.........faaaaaafcccfaaaaaaaaaaccccccccccaaaff....
    ..fa5aaaaaaaff........ffaaaaf.fcccffaaaaaaaaaccccccccccaaaf.....
    ..ffaaaaaffff......fffaaaaaaf.fcccffaaaaaaaaaccccccccccfff......
    ...fffffff........ffaaaaaaaff.fcccffaaaaaaaaafcccccccccffff.....
    ..............ffffaaaaaaaaaf..fcccffaaaaaaaaafccccccccfffaaf....
    .............ffaaaaaaaaaaaf...fcccffaaaaaaaaafffffffff..faaf....
    .............faa5aaaaaaaf.....faaff.faaaaaaaaf.........faa5af...
    ...........ffaaaaaaaafff......faaf...faaaaaaaa........ffaaaaf...
    ..........faaaaaaaaaff........faf.....ffaaaaaaf......ffaaaaff...
    ..........faaaaaaaaff........ffaf.......ffaaaaafffffffaa5aaf....
    ........ffaaaaaaaaff.........faf..........faaaaaaaaaaaaaaaf.....
    .......ffaaaa5afff..........ffaf..........ffaa5aaaaaaaaaaf......
    .......faaaaaaff...........ffaaf...........ffaaaaaaaaaaaaf......
    ......faaaaaaff..........ffaaaaf............ffaaaaaaaaaaf.......
    ......faaa5aafffff.......faaaaf..............ffaaaa5aaaf........
    ......faaaaaafaaaf.......faa5aaf..............fffaaaaff.........
    ......ffaaaaaaaaff.......faaaaaff...............fffff...........
    ........faaaffff.........faaaa5affff............................
    .........................fffaaaaafff............................
    ...........................ffffff...............................
    ................................................................
    ................................................................
    `, SpriteKind.Player)
